version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        MYSQL_DB_HOST: mysql
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database
    container_name: mysql-container