version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - database/var/lib/mysql
      - ./docker-containers/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DB_HOST: mysql
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database